# Generated by Django 6.0.5 on 2026-05-28 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 (Direct)'), (2, 'Scope 2 (Indirect - Energy)'), (3, 'Scope 3 (Value Chain)')])),
                ('category', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('original_value', models.FloatField(blank=True, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(default='kgCO2e', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged (Data Issue)'), ('APPROVED', 'Approved (Locked for Audit)')], default='PENDING', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawIngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Flat File'), ('UTILITY', 'Utility Portal CSV'), ('TRAVEL', 'Travel API JSON')], max_length=50)),
                ('raw_payload', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='ingestion.emissionrecord')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.rawingestionlog'),
        ),
        migrations.AddField(
            model_name='rawingestionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_logs', to='ingestion.tenant'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='ingestion.tenant'),
        ),
    ]
